theme = "modern"
icons = "awesome"

[[block]]
block = "time"
interval = 1
format = "%a %m/%d/%Y %T"

[[block]]
block = "music"
player = "spotify"
buttons = ["prev", "play", "next"]
on_collapsed_click = "spotify"

[[block]]
block = "sound"

[[block]]
block = "net"
device = "wlp4s0"
ssid = true
ip = false 
speed_up = false
speed_down = false
graph_up = false 
interval = 5

[[block]]
block = "disk_space"
path = "/"
alias = ""
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}% {frequency}GHz"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{max}° max, {average}° avg"

[[block]]
block = "memory"
format_mem = "{Mug}GB/{MTg}GB)"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

